config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'

  resources :articles
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_secure_password

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false },
  format: { with: VALID_EMAIL_REGEX }
  before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Your account was updated successfully'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-xs-12">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
    <%= f.label :title %>
    </div>
    <div class="col-sm-6">
      <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-2">
    <%= f.label :description %>
    </div>
    <div class="col-sm-6">
    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-info btn-large' %>
    </div>
  </div>
<% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article 🔩</h1>
  <%= render 'form' %>
  <%= link_to 'Back', articles_path %>
  <%= link_to 'Delete', article_path(@article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<%= render 'shared/article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article 🖋</h1>

  <%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
    <div class="row" align="center">
      <div class="col-md-4 col-md-offset-4">
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
        <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
        <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
      </div>
    </div>
    </ul>
  <% end %>
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <div class="article-actions">
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
    <%= link_to "Back", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Natalia Blog", root_path, class: "navbar-brand", id: "logo" %>    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Create Article", new_article_path %></li>
        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'shared/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About ⛵️</h1>

app/views/pages/index.html.erb
<h1>Hi, I'm Blog 🦭</h1>

app/views/shared/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
          <small>Created by: <%= article.user.username if article.user %>,
                    <%= time_ago_in_words(article.created_at) %> ago,
                    last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
        <div class="article-actions">
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
    <div class="panel-heading">
      <h2 class="panel-title">
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this obj from being saved:
      </h2>
      <div class="panel-body">
      <ul>
        <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
        <% end %>
      </ul>
      </div>
    </div>
    </div>
  </div>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
  <div class="col-xs-12">
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
    <%= f.label :username %>
    </div>
    <div class="col-sm-8">
    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-2">
    <%= f.label :email %>
    </div>
    <div class="col-sm-8">
    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-2">
    <%= f.label :password %>
    </div>
    <div class="col-sm-8">
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
    </div>
  </div>
<% end %>
  <div class="col-xs-4 col-xs-offset-2">
  [ <%= link_to 'Cancel request and Return to Articles Listing', articles_path %> ]
  </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit User Account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Users</h1>
<div align="center">

  <% @users.each do |user| %>
    <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="article-title"><%= link_to user.username, user_path(user) %></li>
        <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
      </div>
    </div>
    </ul>
  <% end %>
<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-5 center">
  <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<%= render 'shared/article', obj: @user.articles %>
<div align="center">
  <%= will_paginate @user_articles %>
</div>